# Generated by Django 5.1.3 on 2025-01-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guitar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.BooleanField(default=True, verbose_name="State")),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="Ceration_date"),
                ),
                (
                    "modify_date",
                    models.DateField(auto_now=True, verbose_name="Modify date"),
                ),
                (
                    "delete_date",
                    models.DateField(auto_now=True, verbose_name="Delete date"),
                ),
                (
                    "brand",
                    models.CharField(
                        help_text="Brand of the guitar (e.g., Fender, Gibson).",
                        max_length=100,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text="Model name or number of the guitar.", max_length=100
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("acoustic", "Acoustic"),
                            ("electric", "Electric"),
                            ("bass", "Bass"),
                            ("classical", "Classical"),
                        ],
                        help_text="Type of guitar.",
                        max_length=20,
                    ),
                ),
                (
                    "string_count",
                    models.PositiveSmallIntegerField(
                        default=6, help_text="Number of strings."
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color of the guitar.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the guitar.",
                        max_digits=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about the guitar.",
                        null=True,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Is the guitar available for sale?"
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="devetechnologies-images"
                    ),
                ),
            ],
            options={
                "verbose_name": "Guitar",
                "verbose_name_plural": "Guitars",
                "ordering": ["brand", "model"],
            },
        ),
    ]
