# Generated by Django 5.1.3 on 2025-01-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guitar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guitar",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
